import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className=" bg-digitalmaker-gray">
      <body className=" bg-digitalmaker-gray text-digitalmaker-offwhite">
        {children}
      </body>
    </html>
  );
}
